### ISSUE TITLE
How to create weights?

### ISSUE THREAD

**Issue by lokeshh** [FluxML/FluxJS.jl#9]
How to create weights for FluxJS? 

I tired by training the model through Flux and then exporting the weights using following code:

```julia
m = Chain(
  Dense(28^2, 32, relu),
  Dense(32, 10),
  softmax)
...<train the model>
weights = Tracker.data.(params(m));
@save "mnist-mlp2.bson" weights
```
But upon loading the BSON I get following error:
`uncaught exception: Array type Core,Float64 not supported.`

**Comment by Roboneet** [comment]
Alternatively,  you could use 
```julia
FluxJS.compile("mnist-mlp2", m, rand(28^2))
```
That will create mnist-mlp2.bson with the weights in a format which flux.js can load

**Comment by lokeshh** [comment]
Thanks! That fixed the problem.
